import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

local Angle = Vector3.up;
Speed = 10000;

local showEnv = false
local envScroll = Vector2.zero

ResetLua = false;

function Update()
	transform:RotateAround(transform.position,Angle,Speed * Time.deltaTime)

	if Input.GetKey(KeyCode.W) then
		Speed = Speed + 1
	end

	if Input.GetKey(KeyCode.S) then
		Speed = Speed - 1
	end

	if Input.GetKey(KeyCode.A) then
		Angle.z = Angle.z + 1
	end

	if Input.GetKey(KeyCode.D) then
		Angle.z = Angle.z - 1
	end
	if Input.GetKey(KeyCode.L) then
Speed = 1
end

end