import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

func:SetPosition(15,1,50)
speed = 1

function Update()
func:SetPosition(func:GetPosition().x,func:GetPosition().y + speed, func:GetPosition().z)
end