import 'System'
import 'UnityEngine'
import 'Assembly-CSharp'	-- The user-code assembly generated by Unity.

cube = this:CreateObject('Cube')
cube:SetCollider()
shield = this:CreateObject('ThisShieldModel')
shield:SetCollider()